### ISSUE TITLE
allow indentation customization for "dumping"

### ISSUE THREAD

**Issue by taylorfoss89** [skeletonkey/Erik#2]
added  `$Data::Dumper::Indent = 1;`  to specify my preferred Data::Dumper indentation styling
for the easiest implementation, you could simply be explicit about the indentation level being set in Erik -- 
`$Data::Dumper::Indent = 2;` (as 2 is the default level for Data::Dumper), that way the user has an idea of what they could configure without going into documentation. Or you could implement it the same you have stack_trace_limit 

```
require Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Maxdepth = $max_depth if $max_depth;
my $dump = Data::Dumper->Dump([$var]);
$Data::Dumper::Maxdepth = 0          if $max_depth;
```

**Comment by skeletonkey** [comment]
I could make a method like "Erik::dump_indent(1);" or "Erik::dump_setting('Indent' , 1);".  The second allows for any of the config/methods available for Data::Dumper.  Which would you prefer?

**Comment by skeletonkey** [comment]
This has been addressed with the new method 'dump_setting'.
